# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-functions-secure-cloud-function-core
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Secure Cloud Function (2nd Gen) Core
    source:
      repo: https://github.com/anshukaira/terraform-google-cloud-functions.git
      sourceType: git
      dir: /modules/secure-cloud-function-core
    version: 0.7.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: cloud_function2_gcs_source
        location: examples/cloud_function2_gcs_source
      - name: cloud_function2_pubsub_trigger
        location: examples/cloud_function2_pubsub_trigger
      - name: secure_cloud_function_bigquery_trigger
        location: examples/secure_cloud_function_bigquery_trigger
      - name: secure_cloud_function_internal_server
        location: examples/secure_cloud_function_internal_server
      - name: secure_cloud_function_with_sql
        location: examples/secure_cloud_function_with_sql
  interfaces:
    variables:
      - name: project_id
        description: The project ID to deploy to.
        varType: string
        required: true
      - name: network_id
        description: VPC network ID which is going to be used to connect the WorkerPool.
        varType: string
        required: true
      - name: project_number
        description: The project number to deploy to.
        varType: number
      - name: encryption_key
        description: The KMS Key to Encrypt Event Arc, source Bucket, docker repository.
        varType: string
        required: true
      - name: function_name
        description: The name of the Cloud Function to create.
        varType: string
        required: true
      - name: function_description
        description: The description of the Cloud Function to create.
        varType: string
        defaultValue: ""
      - name: labels
        description: Labels to be assigned to resources.
        varType: map(any)
        defaultValue: {}
      - name: location
        description: Cloud Function deployment location.
        varType: string
        defaultValue: us-east4
      - name: runtime
        description: The runtime in which the function will be executed.
        varType: string
        required: true
      - name: entry_point
        description: The name of a method in the function source which will be invoked when the function is executed.
        varType: string
        required: true
      - name: storage_source
        description: Get the source from this location in Google Cloud Storage.
        varType: |-
          object({
              bucket     = string
              object     = string
              generation = optional(string, null)
            })
      - name: repo_source
        description: The source repository where the Cloud Function Source is stored. Do not use combined with source_path.
        varType: |-
          object({
              project_id   = optional(string)
              repo_name    = string
              branch_name  = string
              dir          = optional(string)
              tag_name     = optional(string)
              commit_sha   = optional(string)
              invert_regex = optional(bool, false)
            })
      - name: build_environment_variables
        description: A set of key/value environment variable pairs to be used when building the Function.
        varType: map(string)
        defaultValue: {}
      - name: event_trigger
        description: A source that fires events in response to a condition in another service.
        varType: |-
          object({
              trigger_region        = optional(string)
              event_type            = string
              service_account_email = string
              pubsub_topic          = optional(string)
              retry_policy          = string
              event_filters = optional(set(object({
                attribute       = string
                attribute_value = string
                operator        = optional(string)
              })))
            })
        required: true
      - name: service_config
        description: Details of the service
        varType: |-
          object({
              max_instance_count    = optional(string, 100)
              min_instance_count    = optional(string, 1)
              available_memory      = optional(string, "256M")
              timeout_seconds       = optional(string, 60)
              runtime_env_variables = optional(map(string), null)
              runtime_secret_env_variables = optional(set(object({
                key_name   = string
                project_id = optional(string)
                secret     = string
                version    = string
              })), null)
              secret_volumes = optional(set(object({
                mount_path = string
                project_id = optional(string)
                secret     = string
                versions = set(object({
                  version = string
                  path    = string
                }))
              })), null)
              vpc_connector                  = string
              vpc_connector_egress_settings  = optional(string, "ALL_TRAFFIC")
              ingress_settings               = optional(string, "ALLOW_INTERNAL_AND_GCLB")
              service_account_email          = string
              all_traffic_on_latest_revision = optional(bool, true)
            })
        required: true
      - name: force_destroy
        description: Set the `force_destroy` attribute on the Cloud Storage.
        varType: bool
        defaultValue: false
      - name: bucket_cors
        description: Configuration of CORS for bucket with structure as defined in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#cors.
        varType: any
        defaultValue:
          - max_age_seconds: 0
            method:
              - GET
            origin:
              - https://*.cloud.google.com
              - https://*.corp.google.com
              - https://*.corp.google.com:*
              - https://*.cloud.google
              - https://*.byoid.goog
            response_header: []
      - name: bucket_lifecycle_rules
        description: The bucket's Lifecycle Rules configuration.
        varType: |-
          list(object({
              # Object with keys:
              # - type - The type of the action of this Lifecycle Rule. Supported values: Delete and SetStorageClass.
              # - storage_class - (Required if action type is SetStorageClass) The target Storage Class of objects affected by this Lifecycle Rule.
              action = any

              # Object with keys:
              # - age - (Optional) Minimum age of an object in days to satisfy this condition.
              # - created_before - (Optional) Creation date of an object in RFC 3339 (e.g. 2017-06-13) to satisfy this condition.
              # - with_state - (Optional) Match to live and/or archived objects. Supported values include: "LIVE", "ARCHIVED", "ANY".
              # - matches_storage_class - (Optional) Storage Class of objects to satisfy this condition. Supported values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, STANDARD, DURABLE_REDUCED_AVAILABILITY.
              # - matches_prefix - (Optional) One or more matching name prefixes to satisfy this condition.
              # - matches_suffix - (Optional) One or more matching name suffixes to satisfy this condition
              # - num_newer_versions - (Optional) Relevant only for versioned objects. The number of newer versions of an object to satisfy this condition.
              condition = any
            }))
        defaultValue:
          - action:
              type: Delete
            condition:
              age: 0
              days_since_custom_time: 0
              days_since_noncurrent_time: 0
              num_newer_versions: 3
              with_state: ARCHIVED
    outputs:
      - name: artifact_registry_repository_id
        description: The ID of the Artifact Registry created to store Cloud Function images.
      - name: cloudbuild_worker_pool_id
        description: The ID of the Cloud Build worker pool created to build Cloud Function images.
      - name: cloudfunction_bucket
        description: The Cloud Function source bucket.
      - name: cloudfunction_bucket_name
        description: Name of the Cloud Function source bucket.
      - name: cloudfunction_name
        description: Name of the created service.
      - name: cloudfunction_url
        description: The URL on which the deployed service is available.
      - name: eventarc_google_channel_id
        description: The ID of the Google Eventarc Channel.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/accesscontextmanager.policyAdmin
          - roles/orgpolicy.policyAdmin
      - level: Project
        roles:
          - roles/owner
          - roles/iam.serviceAccountUser
          - roles/certificatemanager.editor
      - level: Project
        roles:
          - roles/resourcemanager.folderAdmin
          - roles/resourcemanager.projectCreator
          - roles/resourcemanager.projectDeleter
          - roles/compute.xpnAdmin
          - roles/iam.serviceAccountTokenCreator
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
      - cloudfunctions.googleapis.com
      - run.googleapis.com
      - cloudbuild.googleapis.com
      - artifactregistry.googleapis.com
      - pubsub.googleapis.com
      - eventarc.googleapis.com
      - iamcredentials.googleapis.com
      - accesscontextmanager.googleapis.com
      - iam.googleapis.com
      - cloudbilling.googleapis.com
      - cloudkms.googleapis.com
      - bigquery.googleapis.com
      - certificatemanager.googleapis.com
      - sql-component.googleapis.com
      - sqladmin.googleapis.com
      - servicenetworking.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.74, < 7.0"
      - source: hashicorp/google-beta
        version: < 7.0
